### ISSUE TITLE
Wrong error output

### ISSUE THREAD

**Issue by Punktraum** [richardhj/contao-email-token-login#10]
The extension works fine for me after first tests (Contao 4.12.13) - thanks for that!

However, I noticed the following: if I (intentionally) use a wrong email address, I don't get the error message from the module, but (probably) the one from Contao's own login module ("_Anmeldung fehlgeschlagen (Benutzernamen und Passwörter unterscheiden zwischen Groß- und Kleinschreibung)!_") This is a bit awkward when this message mentions something about username and password, which you actually don't need now thanks to this extension.

Did I make a mistake or is this a bug?
 
Also, the output from the module after sending the (correct) email address is in English ("_Please check your inbox to proceed with the login._") - can I localize this somehow (DE)?

**Comment by richardhj** [comment]
Should be fixed by now.

**Comment by Punktraum** [comment]
The fix works in principle, the messages when sending the e-mail address are displayed correctly and in the correct language - big thanks!

However, there is an error after clicking on the "Sign up" link in the email, the log (var/logs) shows:
`[2021-11-30T11:48:37.180498+01:00] request.CRITICAL: Uncaught PHP Exception TypeError: "Richardhj\ContaoEmailTokenLoginBundle\Controller\TokenLogin::invalidateToken(): Argument #1 ($tokenId) must be of type int, string given, called in /home/httpd/vhosts/host/tld/vendor/richardhj/contao-email-token-login/src/Controller/TokenLogin.php on line 93" at /home/httpd/vhosts/host/tld/vendor/richardhj/contao-email-token-login/src/Controller/TokenLogin.php line 131 {"exception":"[object] (TypeError(code: 0): Richardhj\\ContaoEmailTokenLoginBundle\\Controller\\TokenLogin::invalidateToken(): Argument #1 ($tokenId) must be of type int, string given, called in /home/httpd/vhosts/host/tld/vendor/richardhj/contao-email-token-login/src/Controller/TokenLogin.php on line 93 at /home/httpd/vhosts/host/tld/vendor/richardhj/contao-email-token-login/src/Controller/TokenLogin.php:131)"} []`

**Comment by richardhj** [comment]
Ok, please continue testing :)

**Comment by Punktraum** [comment]
Now it works perfect!

Thanks!!!
