### ISSUE TITLE
Fehler nach Aufruf des Login-Links

### ISSUE THREAD

**Issue by rustykowski** [richardhj/contao-email-token-login#2]
Hallo Richard,
ich versuche, deine Erweiterung unter Contao 4.7.5 und PHP 7.2 einzusetzen.
Die Notification wird auch bereits verschickt.
Der Link sieht etwa so aus: http://example.com/_contao/t_login/NAPLfE06LjdX7FCBspAtpSHDyITBN4rtBFhZx3pqmnI

Ruft man den Link auf, zeigt Contao eine Fehlerseite.
Im Error-Log steht:

`request.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "Controller "richardhj.contao_email_token_login.controller.token_login" cannot be fetched from the container because it is private. Did you forget to tag the service with "controller.service_arguments"?" at /usr/www/users/[path]/vendor/symfony/http-kernel/Controller/ContainerControllerResolver.php line 71 {"exception":"[object] (InvalidArgumentException(code: 0): Controller \"richardhj.contao_email_token_login.controller.token_login\" cannot be fetched from the container because it is private. Did you forget to tag the service with \"controller.service_arguments\"? at /usr/www/users/[path]/vendor/symfony/http-kernel/Controller/ContainerControllerResolver.php:71, Error(code: 0): Class 'richardhj.contao_email_token_login.controller.token_login' not found at /usr/www/users/[path]/vendor/symfony/http-kernel/Controller/ControllerResolver.php:133)"} []`

Habe ich etwas falsch konfiguriert, oder liegt es an deinem Code?

**Comment by richardhj** [comment]
Besteht der Fehler in v1.1.1 immer noch?

**Comment by rustykowski** [comment]
mit v1.1.1 klappt es jetzt fehlerfrei. Vielen Dank! Was eine Zeile Code doch bewirken kann … ;-)
