### ISSUE TITLE
Immediate invalidation causes problems

### ISSUE THREAD

**Issue by rustykowski** [richardhj/contao-email-token-login#3]
Hallo Richard,
der Token wird ja einerseits nach Ablauf von 48 Stunden invalidiert, andererseits aber auch sofort nach Aufruf des Links.
Nach unseren Erfahrungen führt Letzteres relativ oft zu Problemen in Zusammenhang mit Virencheckern und ähnlicher Security-Software. Da werden dann Links gerne mal vorab von einer Software geprüft, bevor der User überhaupt die E-Mail angezeigt bekommt. Damit sind die Links dann schon nicht mehr gültig, wenn sie geklickt werden.

Meine Frage: Könnte man das sofortige Invalidieren nach dem ersten Aufruf abschalten, so dass nur noch das Zeitlimit über die Gültigkeit des Tokens entscheidet? Oder die Anzahl der möglichen Aufrufe auf mehr als 1 begrenzen?

**Comment by richardhj** [comment]
Das Login per Link darf nur auf POST requests funktionieren. Ich habe unter ab1ab34e0f6692136d29adf529ec99f2b19c558a eine Lösung begonnen.

**Comment by rustykowski** [comment]
hui, du bist ja wieder schnell. Sag gern bescheid, wenn ich etwas testen soll.

**Comment by richardhj** [comment]
Gerne.

Bitte installiere die neue Version, bearbeite dafür die composer.json und füge setze den Eintrag für die Erweiterung wie folgt:
`"richardhj/contao-email-token-login": "dev-master as 1.2.0"`.
Dann über die Konsole "composer update" bzw. den Contao Manager "Pakete aktualisieren".

Es ist keine weitere Änderung notwendig.

Falls du HTML-Emailis verschickst, empfehle ich folgenden Text zu verwenden:

```
Bitte klicken Sie auf folgenden Button, um sich auf der Webseite anzumelden.

##login_form_html##

Wenn der Button nicht funktioniert, rufen Sie bitte ##link## manuell auf.
```

**Comment by richardhj** [comment]
Wir müssen dann auch gucken, ob das ursprüngliche Problem gelöst ist. Ggf. hast du ja so einen E-Mail-Client

**Comment by rustykowski** [comment]
Großartig, danke Richard! Ich muss kurz mit dem Kunden kommunizieren, werde die neue Version voraussichtlich in den nächsten 1 bis 2 Tagen installieren und testen. Melde mich …

**Comment by rustykowski** [comment]
Leider negativ. Ich werde nicht eingeloggt, weder mit HTML-Button noch über den Link.

**Comment by richardhj** [comment]
Mmh, da brauche ich mehr Infos. Wie schaut der Quellcode der Weiterleitungsseite aus? Ggf. Zugriff auf das System?

**Comment by rustykowski** [comment]
Offenbar hat deine Änderung gut funktioniert. Die Anwender, die vorher Probleme mit dem Login hatten, können sich nun einwandfrei anmelden, sowohl per Formularbutton als auch über den Link.
Vielen Dank noch mal!
