### ISSUE TITLE
Not working with Contao 4.9.14

### ISSUE THREAD

**Issue by sebmeg** [richardhj/contao-email-token-login#7]
Modul is not working.
I created a notification, the module and put it on the website but if i put a username in the field and send nothing happens. No Errorlog. 

Also the translations are not visible. 
Only "token_login" for the Module and "member_token_login" for the Notification are visible.

**Comment by cmartin6** [comment]
I can confirm this. System log says "Invalid password submitted for username "<<username>>"

**Comment by ameotoko** [comment]
I have an updated branch in [my fork](https://github.com/ameotoko/contao-email-token-login/tree/4.12), which works in 4.12 (I think it should work fine with ^4.10, but I did not test it).

I would provide a PR, but I don't know how to keep it compatible with legacy versions.
